language: rust

cache:
  directories:
    - "$HOME/.cache/coursier/v1"
    - "$HOME/.sbt/boot/"
    - "$HOME/bin"

# build matrix
rust: 1.39.0
matrix:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
    - name: "OSX"
      os: osx
      osx_image: xcode10.1
    - name: CentOS 7
      os: linux
      env: IMAGE=centos7 INDOCKER="docker exec target"
    - name: CentOS 8
      os: linux
      env: IMAGE=centos8 INDOCKER="docker exec target"

services:
  - docker

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/

before_install:
  - ./.travis_scripts/maybe-start-docker.sh
  - ${INDOCKER} ./.travis_scripts/maybe-install-rust.sh
  - openssl aes-256-cbc -K $encrypted_487cf28eaba8_key -iv $encrypted_487cf28eaba8_iv
    -in tests/src/test/resources/service-keys.conf.enc -out tests/src/test/resources/service-keys.conf -d
install:
  - ${INDOCKER} ./.travis_scripts/maybe-install-sbt.sh

before_script:
  # needed for tests to run
  - ${INDOCKER} rustup component add rustfmt-preview
script:
  - "${INDOCKER} ./.travis_scripts/cross-test.sh"

# upload libs to github release. runs a release build first
before_deploy: ${INDOCKER} ./.travis_scripts/build-release.sh
deploy:
  skip_cleanup: true
  provider: releases
  api-key:
    secure: "byBjVIn1BA2Thk2ksKsj87b1WvLsF4Td+DfAZVH+N4cFRowdm8f9boBgLp24DcvIzWjaBHSKzhrqe0ACaInEhMEC6K8xfkZrwd4k8/2yDNkrTnzQcjrEF0FKxvAakoQwnYPQGpnbpzDhfKf5PhtpAVHmrJAnxx6E7HzaS+/EX98F1rAd4zcq84ih8tksp2G97aQcniEEozNJHrKfjo03dt48m8seRx3LNOO0TMogPz59y+9FB8YJeEGlfTb0hD2jC7VMZ0ULbLM3BzijOaKa3OitRkST9w06VdMxdgLrVDlf1Eeej5kaZL32G+cyaRUSaPNqjoSZezI+AWqBuJaAT+o+TzrwmJMU2RSkP/3zZXBN3dwkWF3ilDTwxygsfDhkhppC/En+4PtqFzO6odWCS8ttywUAMQvBWwgByzW8GM+vV4MoBvGGZYxZogu9sURxZiW5JvrfFsNJ2BuhbA/3gDpbfB5BmNXQ78KApirwqLXAcVXc1S3QfP3TUhWe2tAeHsRT3bOpVAKRAWBrbg4xmMNoTlEg6Op6kScqS86VVnKxHKDoU7dC68bdzm/+tXUiFxWA9LmYHqt5jxiGuZF8UZLEBaj9Xx7MByXwJkyEy/WmcxPMuP4Thwpz36yMuXC7Uf9GcHTkwR5DOAPolATLF4p5fnI8xuQn/gTIxC5TOoQ="
  file_glob: true
  file: release_artifacts/*
  # only publish on tag
  on:
    tags: true
  name: Version $TRAVIS_TAG
