[package]
name = "ironoxide-java"
version = "0.5.0"
authors = ["IronCore Labs <info@ironcorelabs.com>"]
build = "build.rs"
edition = "2018"

[lib]
name = "ironoxide_java"
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
itertools = "0.8"
ironoxide = { git = "https://github.com/IronCoreLabs/ironoxide.git", branch = "25-device-context-format"}
chrono = "0.4"

[build-dependencies]
env_logger = "0.7"
rust_swig = { git = "https://github.com/Dushistov/rust_swig.git", rev = "f1af10fb0c1c96c9153857d18ea06a7c0644e265"}
bindgen = "0.51"