[package]
name = "ironoxide-java"
version = "0.3.0"
authors = ["IronCore Labs <info at ironcorelabs.com>"]
build = "build.rs"
edition = "2018"

[lib]
name = "ironoxide_java"
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
itertools = "0.8"
ironoxide = {git = "https://github.com/IronCoreLabs/ironoxide.git", rev="5ba7f1bff5ec1fcdf25d57f517ed0741cdf2d8ca"}
chrono = { version = "0.4", features = ["serde"] }

[build-dependencies]
env_logger = "0.6"
log = "0.4"
rust_swig = {git = "https://github.com/Dushistov/rust_swig.git", rev="a0ae74a" }
bindgen = "0.46"
