[package]
name = "ironoxide-java"
version = "0.1.0"
authors = ["IronCore Labs <info at ironcorelabs.com>"]
build = "build.rs"
edition = "2018"

[lib]
name = "ironoxide_java"
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
itertools = "0.8"
ironrust = {git = "ssh://git@github.com/ironcorelabs/ironrust.git", rev="ee858dd" }
chrono = { version = "0.4", features = ["serde"] }

[build-dependencies]
env_logger = "0.6"
log = "0.4"
rust_swig = "0.3.0"
bindgen = "0.46"
