[package]
name = "ironoxide-cpp"
version = "0.13.0"
authors = ["IronCore Labs <info@ironcorelabs.com>"]
build = "../common/build.rs"
edition = "2018"

[lib]
name = "ironoxide_shared"
path = "../common/lib.rs"
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
itertools = "0.9.0"
ironoxide = { version = "0.21.0", features = ["blocking", "beta"] }
chrono = "0.4"
serde_json = "~1.0"

[build-dependencies]
env_logger = "0.7"
rust_swig = { git = "https://github.com/coltfred/rust_swig.git", branch = "move-comments-enum" }
bindgen = "0.53"
regex = "~1.3"
cfg-if = "~0.1.0"

[features]
default = ["cpp"]
cpp = []