[package]
name = "ironoxide-android"
version = "0.12.1"
authors = ["IronCore Labs <info@ironcorelabs.com>"]
build = "../common/build.rs"
edition = "2018"

[lib]
path = "../common/lib.rs"
name = "ironoxide_android"
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
itertools = "0.9.0"
ironoxide = { version = "0.21.0", features = ["blocking", "beta"] }
chrono = "0.4"
serde_json = "~1.0"
jni-sys = "0.3.0"

[build-dependencies]
env_logger = "0.7"
rust_swig = { git = "https://github.com/Dushistov/rust_swig.git", rev = "cfd12fb7406f9f2774832c051ce7b4e6c2e193d7" }
bindgen = "0.53"
regex = "~1.3"

[features]
default = ["android"]
android = []